import type { Course } from "./types";

// Courses the student is already registered for (mirrors My Courses page).
// Used to disable/flag duplicate registration attempts here.
export const alreadyRegisteredCodes: string[] = ["CS-301", "MATH-210", "ENG-205", "CS-322"];

// Courses the student has already completed — used for prerequisite checks.
export const completedCourseCodes: string[] = ["CS-101", "MATH-101", "ENG-100"];

export const departments = [
  "Computer Science",
  "Mathematics",
  "Software Engineering",
  "Artificial Intelligence",
  "English",
  "General Education",
];

export const mockCourses: Course[] = [
  {
    id: "crs-1",
    code: "CS-301",
    name: "Database Systems",
    description:
      "Relational database design, SQL, normalization, transactions, and an introduction to NoSQL data stores.",
    category: "core",
    department: "Computer Science",
    instructor: "Dr. Ahmed Khan",
    credits: 3,
    level: "300",
    seatsTotal: 60,
    seatsTaken: 20,
    schedule: { days: ["Mon", "Wed"], startTime: "09:00", endTime: "10:15", room: "Room 204" },
    prerequisites: ["CS-101"],
  },
  {
    id: "crs-2",
    code: "CS-302",
    name: "Web Engineering",
    description:
      "Full-stack web application development covering REST APIs, modern frontend frameworks, and deployment.",
    category: "core",
    department: "Computer Science",
    instructor: "Prof. Imran Qureshi",
    credits: 3,
    level: "300",
    seatsTotal: 50,
    seatsTaken: 48,
    schedule: { days: ["Mon", "Wed"], startTime: "10:00", endTime: "11:15", room: "Room 118" },
    prerequisites: ["CS-101"],
  },
  {
    id: "crs-3",
    code: "CS-305",
    name: "Artificial Intelligence",
    description:
      "Search algorithms, knowledge representation, machine learning fundamentals, and intelligent agents.",
    category: "core",
    department: "Artificial Intelligence",
    instructor: "Dr. Sana Malik",
    credits: 3,
    level: "300",
    seatsTotal: 45,
    seatsTaken: 45,
    schedule: { days: ["Mon"], startTime: "10:00", endTime: "12:00", room: "Lab 3" },
    prerequisites: ["CS-101", "MATH-201"],
  },
  {
    id: "crs-4",
    code: "CS-307",
    name: "Software Engineering",
    description:
      "Software development lifecycle, agile methodology, testing strategies, and team-based capstone project work.",
    category: "core",
    department: "Software Engineering",
    instructor: "Eng. Bilal Ahmed",
    credits: 4,
    level: "300",
    seatsTotal: 40,
    seatsTaken: 12,
    schedule: { days: ["Tue", "Thu"], startTime: "13:30", endTime: "15:00", room: "Room 210" },
    prerequisites: ["CS-101"],
  },
  {
    id: "crs-5",
    code: "MATH-201",
    name: "Discrete Mathematics",
    description: "Logic, set theory, combinatorics, graph theory, and proof techniques for computer science.",
    category: "core",
    department: "Mathematics",
    instructor: "Dr. Farah Zaidi",
    credits: 3,
    level: "200",
    seatsTotal: 70,
    seatsTaken: 30,
    schedule: { days: ["Tue", "Thu"], startTime: "09:00", endTime: "10:15", room: "Room 118" },
    prerequisites: ["MATH-101"],
  },
  {
    id: "crs-6",
    code: "MATH-210",
    name: "Linear Algebra",
    description: "Vector spaces, matrices, eigenvalues, and linear transformations with applications.",
    category: "core",
    department: "Mathematics",
    instructor: "Prof. Imran Qureshi",
    credits: 3,
    level: "200",
    seatsTotal: 55,
    seatsTaken: 40,
    schedule: { days: ["Mon", "Wed"], startTime: "11:00", endTime: "12:15", room: "Room 118" },
    prerequisites: ["MATH-101"],
  },
  {
    id: "crs-7",
    code: "ENG-101",
    name: "Technical Communication",
    description: "Writing clear technical documentation, reports, and presentations for engineering audiences.",
    category: "gen-ed",
    department: "English",
    instructor: "Dr. Waqas Anjum",
    credits: 2,
    level: "100",
    seatsTotal: 80,
    seatsTaken: 22,
    schedule: { days: ["Fri"], startTime: "13:00", endTime: "14:30", room: "Online" },
    prerequisites: [],
  },
  {
    id: "crs-8",
    code: "ENG-205",
    name: "Technical Writing",
    description: "Advanced technical writing for software documentation, proposals, and research papers.",
    category: "gen-ed",
    department: "English",
    instructor: "Dr. Sana Malik",
    credits: 2,
    level: "200",
    seatsTotal: 60,
    seatsTaken: 60,
    schedule: { days: ["Tue"], startTime: "13:30", endTime: "15:00", room: "Online" },
    prerequisites: ["ENG-101"],
  },
  {
    id: "crs-9",
    code: "CS-322",
    name: "Operating Systems Lab",
    description: "Hands-on lab covering process scheduling, memory management, and concurrency primitives.",
    category: "elective",
    department: "Computer Science",
    instructor: "Eng. Bilal Ahmed",
    credits: 1,
    level: "300",
    seatsTotal: 30,
    seatsTaken: 18,
    schedule: { days: ["Thu"], startTime: "16:00", endTime: "18:00", room: "Lab 3" },
    prerequisites: ["CS-101"],
  },
  {
    id: "crs-10",
    code: "CS-410",
    name: "Machine Learning",
    description: "Supervised and unsupervised learning, neural networks, and applied model evaluation.",
    category: "elective",
    department: "Artificial Intelligence",
    instructor: "Dr. Ahmed Khan",
    credits: 3,
    level: "400",
    seatsTotal: 35,
    seatsTaken: 9,
    schedule: { days: ["Tue", "Thu"], startTime: "10:00", endTime: "11:15", room: "Room 204" },
    prerequisites: ["CS-305"],
  },
  {
    id: "crs-11",
    code: "SE-320",
    name: "Cloud & Distributed Systems",
    description: "Distributed systems fundamentals, cloud architecture patterns, and scalability trade-offs.",
    category: "elective",
    department: "Software Engineering",
    instructor: "Prof. Imran Qureshi",
    credits: 3,
    level: "300",
    seatsTotal: 40,
    seatsTaken: 16,
    schedule: { days: ["Mon", "Wed"], startTime: "13:30", endTime: "14:45", room: "Room 210" },
    prerequisites: ["CS-301"],
  },
  {
    id: "crs-12",
    code: "GE-150",
    name: "Ethics in Technology",
    description: "Philosophical and practical exploration of ethical issues in computing and AI.",
    category: "gen-ed",
    department: "General Education",
    instructor: "Dr. Waqas Anjum",
    credits: 2,
    level: "100",
    seatsTotal: 90,
    seatsTaken: 34,
    schedule: { days: ["Fri"], startTime: "10:00", endTime: "11:30", room: "Room 118" },
    prerequisites: [],
  },
  {
    id: "crs-13",
    code: "MATH-301",
    name: "Probability & Statistics",
    description: "Probability theory, distributions, statistical inference, and hypothesis testing.",
    category: "core",
    department: "Mathematics",
    instructor: "Dr. Farah Zaidi",
    credits: 3,
    level: "300",
    seatsTotal: 50,
    seatsTaken: 44,
    schedule: { days: ["Tue", "Thu"], startTime: "11:30", endTime: "12:45", room: "Room 118" },
    prerequisites: ["MATH-201"],
  },
  {
    id: "crs-14",
    code: "SE-410",
    name: "DevOps & CI/CD",
    description: "Continuous integration, deployment pipelines, containerization, and infrastructure as code.",
    category: "elective",
    department: "Software Engineering",
    instructor: "Eng. Bilal Ahmed",
    credits: 3,
    level: "400",
    seatsTotal: 30,
    seatsTaken: 30,
    schedule: { days: ["Wed"], startTime: "14:00", endTime: "16:00", room: "Lab 3" },
    prerequisites: ["CS-307"],
  },
  {
    id: "crs-15",
    code: "GE-200",
    name: "Entrepreneurship Fundamentals",
    description: "Startup fundamentals — ideation, business models, funding, and go-to-market strategy.",
    category: "gen-ed",
    department: "General Education",
    instructor: "Dr. Sana Malik",
    credits: 2,
    level: "200",
    seatsTotal: 70,
    seatsTaken: 25,
    schedule: { days: ["Fri"], startTime: "14:30", endTime: "16:00", room: "Room 210" },
    prerequisites: [],
  },
];